<number*> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<integer> ::= <number*><integer> | <number*>
<float> ::= <integer>"."<integer>
<numeric_value> ::= <float> | <integer>

<alphabet_lower*> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
<alphabet_upper*> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
<alphabet*> ::= <alphabet_lower*> | <alphabet_upper*>
<identifier!> ::= <identifier_head*><identifier_rest!*> | <identifier_head*>
<identifier_head*> ::= <alphabet*> | "_"
<identifier_rest!*> ::= <unicode_char*><identifier_rest!*> | <unicode_char*>

<quote_double> ::= '"'
<quote_single> ::= "'"
<string_value> ::= <quote_double><quote_double> | <quote_double> <string_content*> <quote_double>
<string_content*> ::= <string_character*><string_content*> | <string_character*>
<string_character*> ::= " " | "\t" | <unicode_char*>

<immediate_value> ::= <numeric_value> | <string_value>

<expression*> ::= <immediate_value> | <identifier!> | <expression*> <operator> <expression*> | "(" <expression*> ")"
<operator> ::= <arithmetic_operator> | <comparison_operator>
<arithmetic_operator> ::= "+" | "-" | "*" | "/" | "%" | "^"
<comparison_operator> ::= "==" | "!=" | "<" | ">" | "<=" | ">="

<space> ::= <space_base*><space> | <space_base*>
<space_base*> ::= " " | "\t"
